global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservices'
    static_configs:
      - targets:
        - 'auth-service:5000'
        - 'catalog-service:5000'
        - 'order-service:5000'
        - 'payment-service:5000'
        - 'notification-service:5006'
        - 'graphql-gateway:5000'
    metrics_path: /metrics
    scrape_interval: 10s